server:
  port: 8080

jwt:
  secret-key: bhvdfjnvsfnsvjnsjlrfeir984h3x4cc79b237nr47rcn34cyn72cnmx2rm87y4r7n2c73mnfh3o


spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2

        - id: posts-service
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=2
            - name : AuthenticationFilter

        - id: connections-service
          uri: lb://CONNECTIONS-SERVICE
          predicates:
            - Path=/api/v1/connections/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
