spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/usersss
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

jwt:
  secret-key:

server:
  port: 9020
  servlet:
    context-path: /users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka