server:
  port: 9010
  servlet:
    context-path: /posts

spring:
  application:
    name: posts-service
  datasource:
    url: jdbc:postgresql://localhost:5432/inventoryDB
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka