server:
  port: 9040
  servlet:
    context-path: /posts

spring:
  application:
    name: posts-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Postssss
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka